quarkus:
  mongodb:
    database: products
    connection-string: ${MONGO_DB:mongodb://192.168.1.48:27017/products}
  http:
    port: 8888

kafka:
  bootstrap:
    servers: ${CONFIG_KAFKA_BROKERS:PLAINTEXT://192.168.1.48:19092}
mp:
  messaging:
    connector:
      smallrye-kafka:
        schema:
          registry:
            url: ${CONFIG_SCHEMA_REGISTRY_URL:http://192.168.1.48:8081}
        auto:
          register:
            schemas: false
        use:
          latest:
            version: true
    incoming:
      stock-sync:
        connector: smallrye-kafka
        failure-strategy: ignore
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        topic: stock-sync-topic
        group:
          id: order-service-group-01
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false

